### ISSUE TITLE
Visualisation disappears to the right

### ISSUE THREAD

**Issue by lenafm** [datasketch/app-visNetwork#1]
The network viz appears briefly when first loading the app but then disappears and the viz-panel increases its size to the right-hand side (but even when you scroll all the way you can't find the visualisation anymore).

**Comment by brazadas** [comment]
yes this is crazy weird... I was looking at it and it seems it has something to do with shinypanels latest versions: if the network output is within a shinypanels' panel, the width of it keeps increasing and increasing. I say shinypanels latest versions because the deployed app (https://datasketch.shinyapps.io/app-visNetwork/) doesn't behave that way, but when I run it locally it does, did you run it locally @lenafm ?

**Comment by lenafm** [comment]
@brazadas hmm no, for me it happens in the deployed app, I haven't tried to run it locally...

**Comment by jpmarindiaz** [comment]
@brazadas you may need to try it in different browsers

**Comment by brazadas** [comment]
yeah.... The deployed app doesn't behave that way for me neither in firefox nor in chrome... when I run it locally in chrome though it does.
https://datasketch.shinyapps.io/app-visNetwork/
Does this happens to you @jpmarindiaz ?
@lenafm in which browser are you running it?

**Comment by jpmarindiaz** [comment]
It works for me. Remember to test it always inside Datasketch https://www.datasketch.co/dashboard/apps/exec/vis-network

**Comment by lenafm** [comment]
@brazadas I'm using chrome and the issue happens both inside Datasketch and on https://datasketch.shinyapps.io/app-visNetwork/

**Comment by brazadas** [comment]
ok thank you I will look at it

**Comment by brazadas** [comment]
@ddazal there is a problem when a visNetwork object is rendered within a shinypanels' panel: it's width continuously increases (below a reproducible example). I was looking at it and it has to do with the css property `flex-shrink` in the `.panel` class, it is set to 0 but if you set it to 1 it stops behaving this way. Also, when the `width` of the panel is set it works fine. What do you think of this? Is there a way of stopping this without having to set the width of the panel?

```
library(shinypanels)
library(visNetwork)

nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

styles <- "
.panel {
  /* uncomment next line to make it work*/
  /*flex-shrink: 1;*/
}
"

ui <- panelsPage(styles = styles, 
                 panel(title = "f",
                       # uncomment next line to make it work
                       # width = 220, 
                       body = visNetworkOutput("visn")))
  
server <- function(input, output, session) {

  output$visn <- renderVisNetwork({
    visNetwork(nodes, edges, main = "visNetwork minimal example")
  })
  
}

shinyApp(ui, server)
```

**Comment by ddazal** [comment]
@brazadas If setting the custom styles to `.panel` for this particular app works, we should use it until we find a better solution. I think it's more related to how `visNetwork` renders rather than an issue with the `shinypanels` CSS. Either way, I'll check this out.

**Comment by jpmarindiaz** [comment]
I agree, this seems specific to how visNetwork own css behaves, so better try to fix it with custom css styles for the wrapper in this app.

**Comment by brazadas** [comment]
ok
